/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Wed Jul 14 10:06:07 2010"
#define BUILD_TIME (1279127167L)

#define VERSION_NUMBER 0x00000707UL
#define VERSION_FEATURES 0x001feeccUL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x44219264UL
#define VERSION_SANITY2 0xb089d5ecUL

#define VERSION_STRING "0.0.7E7F3"
#define VERSION_ID \
 "Unix SlashEM Version 0.0.7E7F3 - last build Wed Jul 14 10:06:07 2010."
