/*	SCCS Id: @(#)filename.h	3.2	96/05/17 */

/* This source file is generated by 'makedefs'.  Do not edit. */

/* Config Filename */
#ifdef UNIX                
# define NH_CONFIG_FILE     ".slashemrc"
#else
# if defined(MAC) || defined(__BEOS__)
#  define NH_CONFIG_FILE     "Slash'EM Defaults"
# else                     
#  ifdef VMS                
#   define NH_CONFIG_FILE     "slashemini"
/*file2 should be the same as file except with sys$login: prepend*/
#   define NH_CONFIG_FILE2    "sys$login:slashem.ini"
#   define NH_CONFIG_FILE3    "SLASHEM.cnf"
#  else                     
#   if defined(MSDOS) || defined(WIN32)
#    define NH_CONFIG_FILE     "defaults.nh";
#   else                     
#    define NH_CONFIG_FILE     "SLASHEM.cnf"
#   endif
#  endif
# endif
#endif

/* Tile Files*/
#define NETHACK_PLANAR_TILEFILE "SLASHEM1.tib"  /* Planar style tiles */
#define NETHACK_PACKED_TILEFILE "SLASHEM2.tib"  /* Packed style tiles */
#define NETHACK_OVERVIEW_TILEFILE "SLASHEMo.tib" /* thin overview tiles */

/* Environment Options Name */
#define NETHACK_ENV_OPTIONS "SLASHEMOPTIONS"
